let dados = [{
    nome: "Vikings", 
    titulo: "Vikings: Uma Imersão no Mundo dos Guerreiros Nórdicos",
    descricao: "Vikings é uma série de televisão que nos transporta para a era Viking, um período marcado por invasões, batalhas épicas e uma rica mitologia nórdica. A trama gira em torno de Ragnar Lothbrok, um fazendeiro ambicioso que se torna um dos mais famosos líderes vikings de seu tempo. A série acompanha a ascensão de Ragnar e de sua família, explorando temas como lealdade, ambição, fé e os desafios de construir um legado em um mundo violento e imprevisível. Com batalhas visceralmente reais, personagens complexos e uma fotografia deslumbrante, Vikings oferece uma experiência imersiva e emocionante para os fãs de dramas históricos e aventuras.",
    personagens: "Ragnar Lothbrok (Travis Fimmel): O protagonista, um fazendeiro ambicioso que se torna um dos mais famosos líderes vikings. Sua sede de aventura e glória o leva a realizar incursões cada vez mais ousadas, desafiando os deuses e os homens.\nLagertha (Katheryn Winnick): A primeira esposa de Ragnar, uma guerreira feroz e independente. Lagertha é um símbolo de força e liderança, mostrando que as mulheres vikings não eram apenas donas de casa.\nRollo (Clive Standen): Irmão de Ragnar, inicialmente leal, mas que se torna um rival por ambição e poder. Sua jornada é marcada por conflitos internos e lealdades divididas.\nFloki (Gustaf Skarsgård): Um habilidoso construtor de navios e um devoto seguidor dos deuses nórdicos. Floki é um personagem excêntrico e apaixonado, cuja fé o leva a extremos.\nAthelstan (George Blagden): Um monge cristão capturado pelos vikings e posteriormente adotado por Ragnar. Athelstan representa o conflito entre duas culturas e crenças, e sua jornada espiritual é um dos pontos altos da série.\nBjorn Ironside (Alexander Ludwig): Filho de Ragnar e Lagertha, um guerreiro forte e ambicioso que busca superar as conquistas de seu pai. Bjorn é o herdeiro de Ragnar e um dos líderes mais importantes da próxima geração de vikings.\nIvar, o Desossado (Alex Høgh Andersen): Filho de Ragnar e Aslaug, um guerreiro cruel e estrategista brilhante, apesar de sua deficiência física. Ivar é um dos personagens mais complexos e controversos da série.\nOutros personagens importantes incluem Aslaug (Alyssa Sutherland), a segunda esposa de Ragnar; Ecbert (Linus Roache), o rei de Wessex; e Heahmund (Jonathan Rhys Meyers), um bispo cristão que se torna um inimigo e, posteriormente, um aliado de Ivar.\nCada um desses personagens contribui para a rica tapeçaria de Vikings, explorando temas como fé, lealdade, ambição e a natureza humana em um contexto histórico fascinante.",
    imdb: 'Para mais informações, confira na página do <a href="https://www.imdb.com/title/tt2306299/" target="_blank">IMDb</a>, onde a série Vikings possui nota 8.5.',
    tags: "vikings, histórico, ação, aventura, mitologia nórdica, drama, família, poder, religião"
}, 
{
    nome: "Game of Thrones", 
    titulo: "Game of Thrones: Uma Saga Épica de Guerra e Intriga",
    descricao: 'Game of Thrones é uma série de fantasia épica baseada na série de livros "As Crônicas de Gelo e Fogo" de George R.R. Martin. Ambientada em um mundo medieval fictício, a trama gira em torno da luta por poder entre grandes famílias nobres que disputam o Trono de Ferro. A série é conhecida por seus personagens complexos, reviravoltas inesperadas e cenas de batalha espetaculares.',
    personagens: 'Eddard "Ned" Stark (Sean Bean): O honrado Lorde de Winterfell, um homem justo e leal. É um dos pilares da série, mas seu destino trágico marca o início da guerra pelos Sete Reinos.\nCersei Lannister (Lena Headey): Rainha regente de Westeros, manipuladora e ambiciosa. Cersei fará de tudo para proteger sua família e manter o poder, mesmo que isso signifique trair e destruir aqueles que a cercam.\nJaime Lannister (Nikolaj Coster-Waldau): Irmão gêmeo de Cersei e um dos melhores espadachim de Westeros. Conhecido como "O Matador de Reis", Jaime possui uma complexidade que o torna um dos personagens mais fascinantes da série.\nTyrion Lannister (Peter Dinklage): O anão da Casa Lannister, inteligente e sarcástico. Apesar de sua aparência, Tyrion é um estrategista brilhante e um conselheiro leal.\nDaenerys Targaryen (Emilia Clarke): A última Targaryen, exilada e determinada a reconquistar o Trono de Ferro. Com seus dragões, Daenerys se torna uma líder carismática e inspiradora.\nJon Snow (Kit Harington): Filho bastardo de Ned Stark, criado no Norte. Jon se junta à Patrulha da Noite e se torna um líder respeitado, descobrindo segredos sobre sua verdadeira identidade.\nSansa Stark (Sophie Turner): A filha mais velha de Ned Stark, inicialmente ingênua e vaidosa, Sansa evolui ao longo da série e se torna uma mulher forte e determinada.\nArya Stark (Maisie Williams): A filha mais nova de Ned Stark, uma guerreira habilidosa e implacável. Arya busca vingança pela morte de sua família e se torna uma assassina impiedosa.\nBran Stark (Isaac Hempstead Wright): O filho mais novo de Ned Stark, com a habilidade de ver o passado e o futuro. Bran se torna uma figura fundamental na luta contra as forças do inverno.\nTywin Lannister (Charles Dance): Patriarca da Casa Lannister, um homem astuto e calculista.\nEste é apenas um resumo dos principais personagens de Game of Thrones. A série é repleta de personagens complexos e fascinantes, cada um com sua própria história e motivações.\nCada um desses personagens contribui para a rica tapeçaria de Vikings, explorando temas como fé, lealdade, ambição e a natureza humana em um contexto histórico fascinante.',
    imdb: 'Para mais informações, confira na página do <a href="https://www.imdb.com/title/tt0944947/" target="_blank">IMDb</a>, onde a série Game of Thrones possui nota 9.2.',
    tags: "fantasia, medieval, drama, política, guerra, dragões, família, traição, poder, trono de ferro, westeros, lannister, stark, targaryen, baratheon, casas, nobreza, intrigas"
},
{
    nome:"Spartacus",
    titulo: "Spartacus: Uma epopeia de sangue, liberdade e vingança",
    descricao: 'Spartacus é uma série de televisão dramática histórica que reimagina a lenda do gladiador trácio que liderou uma grande revolta de escravos contra a República Romana. A série é conhecida por suas cenas de batalha intensas, personagens complexos e uma narrativa visceral que explora temas como liberdade, opressão, amizade e lealdade.',
    personagens: 'Spartacus (Andy Whitfield / Liam McIntyre): O gladiador trácio que se torna o líder da rebelião de escravos. Forte, corajoso e determinado, Spartacus busca vingança contra os romanos que o escravizaram e a liberdade para seu povo. Sua liderança inspiradora e sua habilidade em combate o tornam uma figura lendária.\nCrixus (Manu Bennett): Um gladiador gaulês feroz e habilidoso, Crixus é um dos aliados mais leais de Spartacus. Impulsivo e apaixonado, ele é um guerreiro nato que se torna um dos líderes mais importantes da rebelião\nLucretia (Lucy Lawless): A esposa ambiciosa e manipuladora de Batiatus, o dono da casa de gladiadores. Lucretia é capaz de grande crueldade para conseguir o que deseja, mas também demonstra momentos de vulnerabilidade e complexidade.\nBatiatus (John Hannah): O dono da casa de gladiadores onde Spartacus e Crixus são forçados a lutar. Ambicioso e calculista, Batiatus busca poder e riqueza a qualquer custo, mesmo que isso signifique trair seus próprios aliados.\nNaevia (Cynthia Addai-Robinson): Uma escrava que se apaixona por Crixus. Forte e determinada, Naevia se junta à rebelião e se torna uma guerreira habilidosa.\nGannicus (Dustin Clare): Um gladiador experiente e charmoso, Gannicus é um mestre da espada e um líder nato. Ele se junta à rebelião de Spartacus e se torna um de seus aliados mais confiáveis.\nDoctore (Peter Mensah): O treinador de gladiadores de Batiatus, um homem sábio e experiente que se torna uma figura paterna para muitos dos gladiadores.\nIlithyia (Viva Bianca): A filha de Batiatus, uma jovem mimada e cruel que se envolve em diversos esquemas para conseguir poder.\nObservação: Esta é apenas uma breve descrição dos personagens principais. A série Spartacus apresenta uma vasta gama de personagens complexos e interessantes, cada um com sua própria história e motivações.',
    imdb: 'Para mais informações, confira na página do <a href="https://www.imdb.com/title/tt1442449/" target="_blank">IMDb</a>, onde a série Spartacus possui nota 8.5.',
    tags: "histórico, ação, drama, gladiadores, escravidão, rebelião, vingança, roma antiga, sangue, luta, liberdade, traição, amizade, lealdade, gladiatório"
},
{
    nome: "Breaking Bad",
    titulo: "Breaking Bad: O Mestre da Química",
    descricao: "Uma série dramática que acompanha a transformação de Walter White, um professor de química doente terminal, em um poderoso chefão do tráfico de metanfetamina. A série explora temas como moralidade, ambição e as consequências de escolhas cruciais.",
    personagens: "Walter White (Bryan Cranston): Um professor de química diagnosticado com câncer que inicia a produção de metanfetamina para garantir o futuro financeiro de sua família.\nJesse Pinkman (Aaron Paul): Um jovem dealer de drogas que se torna parceiro de Walter.\nSkyler White (Anna Gunn): A esposa de Walter, que tenta lidar com as consequências das ações de seu marido.\nHank Schrader (Dean Norris): O cunhado de Walter e agente da DEA que investiga o misterioso fabricante de metanfetamina conhecido como 'Heisenberg'.\nGus Fring (Giancarlo Esposito): Um poderoso traficante de drogas que se torna um aliado e, posteriormente, um inimigo de Walter.\nSaul Goodman (Bob Odenkirk): Um advogado especializado em casos criminais que se torna o advogado de Walter e Jesse.",
    imdb: "Para mais informações, confira na página do <a href='https://www.imdb.com/title/tt0903747/' target='_blank'>IMDb</a>, onde a série Breaking Bad possui nota 9.5.",
    tags: "drama, crime, suspense, drogas, família, moralidade, química, metanfetamina, heisenberg, walter white, jesse pinkman, deserto, novo méxico, crime organizado, anti-herói, decadência, corrupção, escolhas, consequências"
},
{
    nome: "The Last Kingdom",
    titulo: "The Last Kingdom: A Inglaterra dividida",
    descricao: "Uma série de drama histórico que se passa na Inglaterra do século IX, durante a Era Viking. A trama acompanha Uhtred de Bebbanburg, um saxão criado pelos vikings, que luta para unificar a Inglaterra e reconquistar suas terras ancestrais. A série explora temas como lealdade, identidade e a luta por poder em um período de grande instabilidade.",
    personagens: "Uhtred de Bebbanburg (Alexander Dreymon): Um saxão criado pelos vikings que busca reconquistar suas terras e unificar a Inglaterra.\nAlfred, o Grande (David Dawson): O rei de Wessex que luta para unir os reinos anglo-saxões contra os invasores vikings.\nBrida (Emily Cox): Uma guerreira viking feroz e leal a Uhtred.\nAelswith (Eliza Butterworth): A rainha de Wessex, mãe de Edward e esposa de Alfredo.\nRagnar (Nathaniel Martello-White): O irmão adotivo de Uhtred e um guerreiro viking.",
    imdb: "Para mais informações, confira na página do <a href='https://www.imdb.com/title/tt4179452/' target='_blank'>IMDb</a>, onde a série The Last Kingdom possui nota 8.5.",
    tags: "histórico, ação, aventura, vikings, saxões, medieval, inglaterra, guerra, reino unido, uhtred, alfred o grande, família, lealdade, traição, destino, identidade, religião, política, poder"
},
{
    nome: "Blindspot",
    titulo: "Blindspot: Uma Agente Amnésica",
    descricao: "Uma mulher completamente tatuada é encontrada nua em Times Square sem nenhuma identificação. A cada tatuagem descoberta, uma nova pista surge, levando a agentes do FBI a uma conspiração global. A série acompanha a agente Jane Doe, que tenta reconstruir sua memória e descobrir sua verdadeira identidade enquanto trabalha para desvendar os mistérios por trás das tatuagens.",
    personagens: "Jane Doe / Remi (Jaimie Alexander): Uma agente amnésica com o corpo coberto de tatuagens que servem como pistas para uma conspiração global.\nKurt Weller (Sullivan Stapleton): O agente do FBI que lidera a equipe encarregada de investigar os casos relacionados às tatuagens de Jane.\nPatterson (Ashley Johnson): Uma analista brilhante e especialista em criptografia que ajuda a decifrar as tatuagens.\nReade (Rob Brown): Um agente do FBI que se torna um aliado de Jane e Weller.\nZane (Zion Moreno): Um hacker talentoso que se junta à equipe e ajuda a desvendar os mistérios da conspiração.",
    imdb: "Para mais informações, confira na página do <a href='https://www.imdb.com/title/tt4474344/' target='_blank'>IMDb</a>, onde a série Blindspot possui nota 7.3.",
    tags: "mistério, ação, suspense, conspiração, tatuagem, amnésia, FBI, identidade, agente secreto, thriller, investigação, cyberpunk, tecnologia, romance, drama, traição, lealdade, equipe, governo, agência secreta"
},
{
    nome: "House of the Dragon",
    titulo: "House of the Dragon: A Dança dos Dragões",
    descricao: "Uma prequela de Game of Thrones que se passa 200 anos antes dos eventos da série original. A história acompanha a Casa Targaryen em um período de grande instabilidade, onde a sucessão ao Trono de Ferro ameaça dividir a família e desencadear uma guerra civil. A série explora temas como poder, ambição, lealdade e a natureza da família.",
    personagens: "Rhaenyra Targaryen (Emma D'Arcy): A primeira mulher a ser nomeada herdeira ao Trono de Ferro, inteligente e ambiciosa.\nDaemon Targaryen (Matt Smith): O irmão mais novo de Rhaenyra, um guerreiro habilidoso e um tanto rebelde.\nAlicent Hightower (Olivia Cooke): A esposa do rei Viserys e mãe de Aegon II, que se torna uma figura central na disputa pelo trono.\nViserys Targaryen (Paddy Considine): O rei dos Sete Reinos, um governante justo e bem-intencionado, mas enfraquecido por uma doença.\nOtto Hightower (Rhys Ifans): A Mão do Rei e pai de Alicent, um homem ambicioso que busca o poder para sua família.",
    imdb: "Para mais informações, confira na página do <a href='https://www.imdb.com/title/tt11198330/' target='_blank'>IMDb</a>, onde a série House of the Dragon possui nota 8.4.",
    tags: "fantasia, medieval, drama, política, guerra, dragões, família, sucessão, trono, targaryen, westeros, nobreza, intrigas, poder, dança dos dragões"
},
{
    nome: "24 Horas",
    titulo: "24 Horas: Viva um dia de cada vez",
    descricao: "Uma série de suspense político que acompanha Jack Bauer, um agente da Unidade Contra o Terrorismo, em missões de 24 horas para salvar os Estados Unidos de ataques terroristas. A série é conhecida por sua narrativa em tempo real, reviravoltas constantes e dilemas morais enfrentados pelos personagens.",
    personagens: "Jack Bauer (Kiefer Sutherland): Um agente da Unidade Contra o Terrorismo, determinado e disposto a fazer qualquer coisa para proteger seu país.\nChloe O'Brian (Mary Lynn Rajskub): Uma analista de computador brilhante e leal a Jack.\nTony Almeida (Carlos Bernard): Um agente da Unidade Contra o Terrorismo que se torna um aliado de Jack.\nAudrey Raines (Kim Raver): A filha do Presidente dos Estados Unidos e um alvo constante dos terroristas.\nDavid Palmer (Dennis Haysbert): O primeiro presidente afro-americano dos Estados Unidos, um homem justo e determinado a proteger o país.",
    imdb: "Para mais informações, confira na página do <a href='https://www.imdb.com/title/tt0285331/' target='_blank'>IMDb</a>, onde a série 24 Horas possui nota 8.4.",
    tags: "suspense, ação, thriller, terrorismo, contra-terrorismo, política, tempo real, agente secreto, Jack Bauer, CTU, investigação, conspiração, moralidade, dilemas, Washington D.C., Estados Unidos, vigilância, segurança nacional"
},
{
    nome: "Prison Break",
    titulo: "Prison Break: Fuga Impossível",
    descricao: "Uma série de drama e ação que acompanha Michael Scofield, um engenheiro civil que se entrega à prisão para ajudar seu irmão, Lincoln Burrows, que foi condenado injustamente à pena de morte. A série explora os elaborados planos de fuga de Michael e as consequências de suas ações.",
    personagens: "Michael Scofield (Wentworth Miller): Um engenheiro civil que elabora um plano complexo para libertar seu irmão da prisão.\nLincoln Burrows (Dominic Purcell): O irmão de Michael, injustamente condenado à pena de morte.\nSara Tancredi (Sarah Wayne Callies): Uma médica da prisão que se apaixona por Michael e ajuda em sua fuga.\nAlexander Mahone (William Fichtner): Um agente do FBI determinado a capturar Michael e Lincoln.\nVeronica Donovan (Robin Tunney): Uma jornalista investigativa que busca a verdade sobre o caso de Lincoln.",
    imdb: "Para mais informações, confira na página do <a href='https://www.imdb.com/title/tt0455275/' target='_blank'>IMDb</a>, onde a série Prison Break possui nota 8.3.",
    tags: "fuga, prisão, drama, suspense, ação, plano, irmão, lealdade, traição, justiça, corrupção, sistema prisional, sobrevivência, psicológico, thriller, escapismo, amizade, família, conspiração, crime organizado"
},
{
    nome: "Vikings: Valhalla",
    titulo: "Vikings: Valhalla - Uma Nova Saga",
    descricao: "Uma sequência da aclamada série Vikings, ambientada 100 anos após os eventos da série original. A trama acompanha um novo grupo de vikings lendários em suas jornadas de exploração e conquista, enquanto enfrentam desafios e conflitos internos. A série explora temas como família, honra, destino e a busca por um novo lar.",
    personagens: "Leif Eriksson (Sam Corlett): Um explorador viking corajoso e determinado, filho de Erik, o Vermelho.\nFreydis Eriksdotter (Frida Gustavsson): A irmã de Leif, uma guerreira habilidosa e poderosa.\nHarald Hardrada (Leo Suter): Um ambicioso príncipe viking que busca unificar os reinos nórdicos.\nOlaf Haraldson (Jóhannes Haukur Jóhannesson): O irmão mais velho de Harald, um líder religioso e político influente.\nCanute, o Grande (Bradley Freegard): O rei da Dinamarca e da Inglaterra, que busca expandir seu império.",
    imdb: "Para mais informações, confira na página do <a href='https://www.imdb.com/title/tt11311302/' target='_blank'>IMDb</a>, onde a série Vikings: Valhalla possui nota 7.3.",
    tags: "vikings, ação, aventura, histórico, medieval, escandinávia, vikings vs cristãos, família, lealdade, traição, poder, mitologia nórdica, exploração, mar, guerra, Ragnar Lothbrok, Valhalla, sangue, honra, destino"
},
{
    nome: "Stranger Things",
    titulo: "Stranger Things: O Mundo Invertido",
    descricao: "Uma série de ficção científica ambientada nos anos 80 que acompanha um grupo de amigos em uma pequena cidade americana que presenciam eventos sobrenaturais após o desaparecimento de um de seus amigos. A série mistura elementos de terror, aventura e nostalgia.",
    personagens: "Onze (Millie Bobby Brown): Uma garota com poderes telecinéticos que escapa de um laboratório secreto.\nMike Wheeler (Finn Wolfhard): O líder do grupo de amigos e melhor amigo de Eleven.\nDustin Henderson (Gaten Matarazzo): Um garoto inteligente e leal com uma fala arrastada.\nLucas Sinclair (Caleb McLaughlin): Um amigo de Mike e Dustin, apaixonado por tecnologia e jogos.\nWill Byers (Noah Schnapp): O amigo desaparecido que se encontra preso no Mundo Invertido.",
    imdb: "Para mais informações, confira na página do <a href='https://www.imdb.com/title/tt4574334/' target='_blank'>IMDb</a>, onde a série Stranger Things possui nota 8.7.",
    tags: "anos 80, nostalgia, ficção científica, terror, suspense, sobrenatural, mistério, amizade, infância, adolescência, small town, governo, experimentos, criaturas, telecinesia, portal, Hawkins, Upside Down, drama, família, bullying, crescimento"
},
{
    nome: "The Last of Us",
    titulo: "The Last of Us: A Jornada de Joel e Ellie",
    descricao: "Uma série de drama pós-apocalíptico ambientada em um mundo devastado por um fungo que transforma humanos em criaturas monstruosas. Acompanha a jornada de Joel, um contrabandista experiente, e Ellie, uma adolescente imune ao fungo, em uma perigosa missão através dos Estados Unidos.",
    personagens: "Joel Miller (Pedro Pascal): Um contrabandista endurecido pela vida pós-apocalíptica.\nEllie Williams (Bella Ramsey): Uma adolescente imune ao fungo Cordyceps, que dá origem aos Infectados.",
    imdb: "Para mais informações, confira na página do <a href='https://www.imdb.com/title/tt3581920/' target='_blank'>IMDb</a>, onde a série The Last of Us possui uma nota 8.7.",
    tags: "pós-apocalíptico, zumbi, pandemia, sobrevivência, drama, ação, vírus, fungo, cordyceps, Ellie, Joel, relação pai-filha, viagem, Estados Unidos, quarentena, deserto, esperança, humanidade, luto, trauma, amizade, família, moral, escolhas"
},
{
    nome: "How I Met Your Mother",
    titulo: "How I Met Your Mother: A História de Ted Mosby",
    descricao: "Uma comédia romântica que acompanha Ted Mosby em sua busca pelo amor da vida, enquanto ele e seus amigos vivem aventuras e dramas em Nova York. A série narra a história de como Ted conheceu a mãe de seus filhos.",
    personagens: "Ted Mosby (Josh Radnor): Um arquiteto romântico e idealista, sempre à procura do amor verdadeiro. É conhecido por suas histórias sobre o amor e por sua paixão por arquitetura.\nRobin Scherbatsky (Cobie Smulders): Uma jornalista canadense, independente e sarcástica. Apesar de sua fachada durona, possui um coração mole e busca um relacionamento sério.\nBarney Stinson (Neil Patrick Harris): Um mulherengo inveterado, elegante e charmoso. Suas aventuras amorosas e suas leis do jogo são uma constante fonte de comédia na série.\nLily Aldrin (Alyson Hannigan): Uma professora de arte, apaixonada e leal. É a melhor amiga de Robin e a esposa de Marshall.\nMarshall Eriksen (Jason Segel): Um advogado ambientalista, otimista e apaixonado. É o melhor amigo de Ted e o marido de Lily.",
    imdb: "Para mais informações, confira na página do <a href='https://www.imdb.com/title/tt0460649/' target='_blank'>IMDb</a>, onde a série How I Met Your Mother possui uma nota 8.3.",
    tags: "comédia, sitcom, romance, amizade, Nova York, amigos, família, relacionamento, casamento, futuro, nostalgia, humor, cotidiano, amor, busca, história, narrativa, Ted Mosby, Barney Stinson, Robin Scherbatsky, Lily Aldrin, Marshall Eriksen, flashback"
}];
